### ISSUE TITLE
install error: package directory 'callback' does not exist

### ISSUE THREAD

**Issue by fengyunzaidushi** [lonePatient/TorchBlocks#4]
when i run "python setup.py install:
it gives me the error:

```
running bdist_egg
running egg_info
writing torchblocks.egg-info\PKG-INFO
writing dependency_links to torchblocks.egg-info\dependency_links.txt
writing requirements to torchblocks.egg-info\requires.txt
writing top-level names to torchblocks.egg-info\top_level.txt
error: package directory 'callback' does not exist
```

my package is below:
python 3.8
win10
tokenizers 0.13.2
transformers 4.26.1
sacremoses  0.0.53
sentencepiece   0.1.97
scipy  1.10.1
scikit-learn  1.2.1
torchmetrics> 0.11.1

**Comment by lonePatient** [comment]
The problem appears in the setup.py file, and I have updated a version.
