### ISSUE TITLE
resume dataset address and format tips

### ISSUE THREAD

**Issue by hxf829** [lonePatient/TorchBlocks#7]
resume dataset used in ner sample is [resumeNER dataset](https://github.com/GuocaiL/nlp_corpus/tree/main/open_ner_data/ResumeNER) 
the format used in run_task_sequence_labeling_resume_global_pointer.sh is *.char.bmes, not *.txt

**Comment by lonePatient** [comment]
@hxf829 hi，the resume dataset mainly used by the example comes from the  [link](https://modelscope.cn/datasets/damo/resume_ner/summary)

**Comment by hxf829** [comment]
thanks :)
